In [10]:
from ldamodel import TopicModel
import numpy as np

In [2]:
model = TopicModel(model_path='./testmodel/lda.model', dict_path='./testmodel/dictionary.dic')

Loaded the LDA model.
Loaded dictionary.


In [5]:
w_t_p = model.get_word_topic_prob()

In [11]:
test = w_t_p.sum(axis=0)

In [ ]:
import matplotlib.pyplot as plt

In [14]:
np.histogram(test, bins=10000)

(array([405612,   1592,   1286, ...,      0,      0,      1]),
 array([7.25960205e-06, 6.94813977e-05, 1.31703193e-04, ...,
        6.22100772e-01, 6.22162994e-01, 6.22225216e-01]))

In [2]:
import torch

# Your list of indices and values
indices = [[0, 1, 2], [1, 2, 3]]
values = [4.0, 5.0, 6.0]

# Assuming the tensor size is known (3 rows, 4 columns)
tensor_size = (3, 4)

# Create a sparse COO tensor
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=tensor_size)

# Convert the sparse tensor to a dense tensor
dense_tensor = sparse_tensor.to_dense()

print(dense_tensor)
print(sparse_tensor)

tensor([[0., 4., 0., 0.],
        [0., 0., 5., 0.],
        [0., 0., 0., 6.]])
tensor(indices=tensor([[0, 1, 2],
                       [1, 2, 3]]),
       values=tensor([4., 5., 6.]),
       size=(3, 4), nnz=3, layout=torch.sparse_coo)
