In [1]:
from ldamodel import TopicModel
import numpy as np
from read import read_test

In [2]:
model = TopicModel(model_path='./testmodel/lda.model', dict_path='./testmodel/dictionary.dic', num_topics=100, vocab_per_topic_size=10)

Loaded the LDA model.
Loaded dictionary.
Generating new word to topic probability matrix.


In [3]:
test_pd = read_test()

In [4]:
test_article = test_pd.article.iloc[0]

In [5]:
tensor = model.bow_tensor(test_article.lower().split()).to_dense().numpy()

In [6]:
sklearn = model.sklearn_bow([test_article]).toarray()

In [7]:
comparison = sklearn == tensor

In [8]:
np.where(comparison == False)

(array([0, 0, 0]), array([ 53, 250, 789]))

In [9]:
model.sklearn_bow_tensor([test_article, test_article]).size()

torch.Size([2, 956])

In [10]:
sklearn[0][53]

1

In [11]:
model.id2token(789)

'ambulance'

In [12]:
model.new_tau_calc(test_article.split())

array([1.13484810e-06, 6.41214735e-06, 6.01405221e-03, 1.75448602e-04,
       8.43424982e-05, 1.73523625e-03, 2.42710179e-04, 1.53635413e-05,
       1.04504001e-03, 2.11080337e-04, 2.99347003e-04, 5.88691321e-05,
       1.43172149e-05, 1.55919481e-04, 3.46868314e-06, 5.66135902e-07,
       3.28896992e-04, 3.62909006e-03, 1.29151912e-05, 1.41595181e-04,
       1.74487258e-04, 1.09610052e-05, 1.01363012e-04, 9.04446879e-06,
       1.42207363e-06, 1.43677539e-03, 1.12294742e-04, 4.30779001e-04,
       7.63331347e-05, 5.19361823e-04, 8.88580430e-04, 2.43859886e-04,
       3.12833143e-04, 9.01303783e-05, 9.37942570e-06, 3.69726011e-06,
       2.08076136e-03, 6.42014541e-06, 1.19277512e-05, 4.79137097e-06,
       4.78005131e-06, 1.15804717e-06, 1.23740946e-06, 1.14792139e-05,
       7.79293364e-04, 3.07072526e-06, 8.38158060e-06, 1.69182681e-06,
       9.09493308e-05, 4.43065394e-05, 1.41397344e-05, 3.14785174e-03,
       3.87745104e-03, 3.22421552e-04, 3.37978640e-06, 4.90965810e-06,
      

In [13]:
model.tau_calc(test_article.split())

array([1.13483549e-06, 5.76969480e-06, 6.29661290e-03, 1.67911665e-04,
       8.37362086e-05, 1.72572902e-03, 2.35360819e-04, 1.59337834e-05,
       1.08834536e-03, 2.07683031e-04, 1.51213213e-04, 5.93198908e-05,
       1.43172038e-05, 1.56278564e-04, 2.98393623e-06, 5.66123619e-07,
       3.09394448e-04, 4.03917346e-03, 1.29158085e-05, 1.10084720e-04,
       1.67280970e-04, 1.09609951e-05, 1.02227627e-04, 9.30849954e-06,
       1.42206135e-06, 1.60026336e-03, 1.17427249e-04, 4.79798512e-04,
       7.71313666e-05, 9.67099329e-05, 8.87557313e-04, 2.43305931e-04,
       1.77177724e-04, 8.14010336e-05, 9.37939759e-06, 2.64783697e-06,
       2.07814026e-03, 6.31674792e-06, 1.12080026e-05, 4.81972730e-06,
       4.78003177e-06, 1.15803489e-06, 1.23739713e-06, 1.19580026e-05,
       6.98792498e-04, 3.07066351e-06, 7.82525749e-06, 1.69181463e-06,
       3.37378593e-06, 6.50075190e-06, 5.57438716e-06, 3.25591822e-03,
       3.79432041e-03, 2.64658710e-04, 3.37977406e-06, 4.85772570e-06,
      